site_name: Briljant
pages:
- [index.md, Introduction]
- [about.md, About]
- [tutorial.md, Tutorial]
- [examples.md, Examples]
- [reference/index.md, 'Reference', 'Introduction']
- [reference/matrix.md, 'Reference', 'Matrix']
- [reference/dataframe.md, 'Reference', 'Data Frames']

extra_javascript: ["js/highlight.pack.js", "js/extra.js"]
extra_css: ["css/highlight.css", "css/extra.css"]

theme: bootstrap

markdown_extensions: [fenced_code, admonition]
